# This is an example configuration file.
# It should be copied to the suitable directory for your OS and modified there.
# Linux : $HOME/.config/torrenttools/config.yml
# Windows : %AppData%/torrenttools/config.yml

tracker-parameters:
  AlphaRatio:
    pid: example_pid
  BroadcastTheNet:
    pid: example_pid
  PassThePopcorn:
    pid: example_pid
  TorrentLeech:
    pid: example_pid
  UHDBits:
    pid: example_pid

tracker-groups:
  example-group1:
    - AlphaRatio
    - TorrentLeech
  example-group2:
    - udp://tracker.opentrackr.org:1337/announce
    - udp://www.torrent.eu.org:451/announce