name: Package

on:
  push:
    branches: [ develop ]

jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v2
      - name: Install build dependencies
        run:  sudo apt-get install -y libstdc++-10-dev g++-10 gcc-10 cmake libtbb2 libtbb-dev libssl1.1 libssl-dev
      - name: Configure
        run: mkdir build && cd build &&
          cmake -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_BUILD_TYPE=Debug -DTORRENTTOOLS_BUILD_TESTS=OFF .. .
      - name: Build
        run: cmake --build build --target torrenttools
      - name: Generate DEB
        working-directory: build
        run: cpack -G DEB
      - name: Archive DEB package
        uses: actions/upload-artifact@v2
        with:
          name: Linux - ${{ matrix.os }}
          path: "build/*.deb"