name: Package (tarball)

on: workflow_dispatch

jobs:
  package-tarball:
    name: "Create tarball"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install build dependencies
        run: sudo apt-get install -y libstdc++-10-dev g++-10 gcc-10 cmake libssl-dev libtbb-dev libre2-dev libyaml-cpp-dev nlohmann-json3-dev

      - name: Fetch external projects
        run: scripts/fetch_dependencies.sh

      - name: Configure
        run: |
          cmake -S . -B cmake-build-release -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_BUILD_TYPE=Release -DTORRENTTOOLS_BUILD_TESTS=ON

      - name: Build tarball
        working-directory: cmake-build-release
        run: |
          cpack --config CPackSourceConfig.cmake -G TGZ

      - name: Determine Version
        id: cmake_version
        working-directory: cmake-build-release
        run: |
          CMAKE_PROJECT_VERSION=$(grep -oP "(?<=CMAKE_PROJECT_VERSION:STATIC=).*" CMakeCache.txt)
          echo "::set-output name=cmake_project_version::${CMAKE_PROJECT_VERSION}"

      - name: Save tarball as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: torrenttools-${{ steps.cmake_version.outputs.cmake_project_version }}.tar.gz
          path: cmake-build-release/torrenttools-${{ steps.cmake_version.outputs.cmake_project_version }}.tar.gz
          retention-days: 1
