on:
  release:
    types: [created, published, edited]

name: Upload windows installer

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-toolchain
      - uses: actions/checkout@v2
      - name: Configure
        run: |
          mkdir build;
          cmake -G "MinGW Makefiles" -B build -S . \
                 -DCMAKE_BUILD_TYPE=Debug \
                 -DTORRENTTOOLS_BUILD_TESTS=OFF \
                 -DTORRENTTOOLS_BUILD_DOCS=OFF
      - name: Build
        run: cmake --build build --target torrenttools
      - name: Package
        run: ctest .
      - name: Get the version
        id: get_version
        run: |
          release_tag="${{ github.event.release.tag_name }}"
          echo ::set-output name=version::"${release_tag:1}"
      - name: Upload windows installer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/torrenttools-${{ steps.get_version.outputs.version }}.msi
          asset_name: torrenttools-${{ steps.get_version.outputs.version }}.msi
          asset_content_type: application/x-msi