name: Windows

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            make
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-yasm
            mingw-w64-openssl
            mingw-w64-x86_64-intel-tbb
      - uses: actions/checkout@v2
      - name: Configure
        run: |
          mkdir build;
          cmake --help
          cmake -G "MSYS Makefiles" -B build -S . \
                 -DDOTTORRENT_CRYPTO_LIB=openssl \
                 -DDOTTORRENT_MB_CRYPTO_LIB=isal \
                 -DCMAKE_BUILD_TYPE=Debug \
                 -DTORRENTTOOLS_BUILD_TESTS=OFF \
                 -DTORRENTTOOLS_BUILD_DOCS=OFF
      - name: Build
        run: cmake --build build --target torrenttools